name 'apache'
maintainer 'Prashant Atri'
maintainer_email 'prashant_atri2003@yahoo.com'
license 'all_rights'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.1.0'
